permalink: /problem/:title
name: "مرحله ۳"
encoding: utf-8
url: https://marhale3.github.io
baseurl: /
markdown: kramdown

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM

plugins:
  - jekyll-sitemap